# Generated by Django 4.1.1 on 2022-12-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_slot_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
