# Generated by Django 4.1.1 on 2022-12-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_slot_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='app',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
